# .github/workflows/scheduled-builds.yml
name: Generate Excange

on: #[push]
  schedule:
    # Runs "at minute 15  minute " (see https://crontab.guru)
    - cron: '*/15 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Jalankan Skrip
        run: |
          curl -Ss "https://api.comm.miui.com/cspmisc/redirect/foreignExchangesRates" > rate.json
          curl -Ss "https://www.binance.com/bapi/asset/v1/public/asset-service/product/currency" > crypto-rate.json
          echo `date +%s` > last_update.txt
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest_branch
          git add -A
          git commit -am "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
